os: osx
osx_image: xcode11
xcode_workspace: Maccy.xcworkspace
xcode_scheme: MaccyTests
install:
  - brew upgrade swiftlint
script:
  - swiftlint
  - xcodebuild clean build test -scheme Maccy -workspace Maccy.xcworkspace
